INSERT INTO materials (id, material_code, material_name, description, category, unit, is_active, is_micro_alloy, updated_at)
VALUES
(gen_random_uuid(), 'FAALWRS010', 'Al_Wire', 'Al Wire', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAALSH9802', 'Al Shots', 'Al Shots', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAALCBP061', 'Al_Cubes', 'Al Cubes', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFEAL0012', 'FeAl', 'Ferro Aluminium', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAGRPW0039', 'Gr Powder', 'Graphite Powder', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FACAFW0026', 'CaFe', 'CaFe Wire', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), '4100003509', 'LCC', 'LCC', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAALBP0007', 'Al_Bar', 'Aluminium Ingots', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FACPCO0051', 'CPC', 'Calcined Petro Coke', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FACASW0025', 'CaSi', 'Ca-Si Wire', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FACOPR0025', 'Cu', 'Copper', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FASMEL0005', 'ELCSIMN', 'Si Mn Elc', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFCHC0019', 'FeCr-HC', 'HC Ferro Chrome', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFCLCS020', 'FeCr-LC', 'LC Ferro Chrome', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFEMO0018', 'FEMO', 'Ferro Molybdenum', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFENB0013', 'FeNb', 'Ferro Niobium', 'FERRO_ALLOY', 'kg', true, true, NOW()),
(gen_random_uuid(), 'FAFEPH0022', 'FeP', 'Ferro Phosphorus', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFESI0007', 'FeSi', 'Ferro Silicon', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFETH0016', 'FeTi(70%)', 'Ferro Titanium 70%', 'FERRO_ALLOY', 'kg', true, true, NOW()),
(gen_random_uuid(), 'FAHCFM0002', 'HCMN', 'HC Ferro Manganese', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FALCMN0043', 'LCMN', 'LC Ferro Manganese', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'INH_CAL_LIME', 'LIME', 'Lime', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAMCFM0029', 'MCMN', 'MC Ferro Manganese', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAMNMT0004', 'MET_MN', 'Manganese Metal', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FANISQ0023', 'Ni', 'Nickel Square', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'SLAG_SYNTH', 'Syn_Slag', 'Synthetic Slag', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FASIMN0001', 'SiMn', 'Silico Manganese', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFEBO0021', 'FeB', 'Ferro Boron', 'FERRO_ALLOY', 'kg', true, true, NOW()),
(gen_random_uuid(), 'FACAFEAL_W_P', 'CaFeAl', 'CaFeAl', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), '4100005806', 'Ca_Carbide', 'Ca_Carbide', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFEVH0014', 'FeV', 'Ferro Vanadium', 'FERRO_ALLOY', 'kg', true, true, NOW()),
(gen_random_uuid(), 'FAFEBOW021', 'Fe_B_Wire', 'Fe_B_Wire', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FAFENTV056', 'NitroVan', 'NitroVan', 'FERRO_ALLOY', 'kg', true, false, NOW()),
(gen_random_uuid(), 'FACHCAL054', 'Pure_Ca', 'Pure_Ca', 'FERRO_ALLOY', 'kg', true, false, NOW())
ON CONFLICT (material_code) DO UPDATE SET
  material_name = EXCLUDED.material_name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  is_active = EXCLUDED.is_active,
  is_micro_alloy = EXCLUDED.is_micro_alloy,
  updated_at = EXCLUDED.updated_at;
